authors = ["Jonathan Goldfarb <jgoldfar@gmail.com>"]
name = "SimpleGradientDescent"
uuid = "7615ede0-6577-11e8-3606-13ee2db7d2d8"
version = "0.1.0"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]